### ISSUE TITLE
Crashlytics Crash Reports - Instantaneous Crash on Certain Devices

### ISSUE THREAD

**Issue by shubham-stan** [rive-app/rive-react-native#181]
### Description

An instantaneous crash on launch occurs on certain devices even when there is no code related to rive on the project. just bundling the package in the build causes this.

 Devices I am aware of -  Samsung  - Galaxy M11, Note 10+ 5G, VIVO - V2101, Y71, OPPO - F17 PRO.
 
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: r0.b: sa.b: Could not find 'libjnirivebridge.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
       at android.app.ActivityThread.installProvider(ActivityThread.java:5858)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5447)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5386)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)

#### Additional context
This looks similar to https://github.com/realm/realm-java/issues/6812

We have a bunch of features ready to pushed on production using rive but this crash has deterred us from rolling out to production. Can provide additional information if you could hint me in the right direction.

**Comment by HayesGordon** [comment]
Thanks for getting back to us @shubham-stan. Please let me know what you find with 4.1.0 and I'll forward this to the rest of the team.

**Comment by Lukmannudin** [comment]
I am experiencing a similar issue, @shubham-stan, with version 9.3.6.

The error message is:
Unable to get provider androidx.startup.InitializationProvider: k3.c: Fe.b: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

cc: @HayesGordon

**Comment by HayesGordon** [comment]
Hi @Lukmannudin, do you have a reproducible example? If so, could you please share that? We can investigate initializing Rive differently for the React Native runtime.

**Comment by jleprinc** [comment]
Still hapening on version 7.2.0, I see there is a new version of androidx.startup:startup-runtime : 1.2.0, could it fix it?
