### ISSUE TITLE
React native crashes when you change to another screen inside a tab view navigator.

### ISSUE THREAD

**Issue by PeterKassab** [rive-app/rive-react-native#198]
### Description
When i play an animation in one screen nested in tab bar navigation, after changing the screen around two times it crashes,
should i unmount the animation or something like? please help.

### Provide a Repro
<-- 
`import { View } from 'react-native'
import React, { useRef } from 'react'
import Rive from 'rive-react-native'
import { Button } from '../../../components/molecules/Button'

const SpeedTestButton = ({ width, height }) => {
    const riveRef = useRef(null)
    const buttonPressed = useRef(false)

    const handleStateChanges = (machine, name) => {
        switch (name) {
            case 'BlendState':
                buttonPressed.current = true
                break
            case 'ExitState':
                alert('pressed')
                break
        }
    }
    return (
        <View style={{ backgroundColor: 'coral' }}>
            <Rive
                ref={riveRef}
                resourceName="speedtest_start_button"
                autoplay={true}
                stateMachineName="MainState"
                onStateChanged={handleStateChanges}
                style={{ width, height }}
            />
            <Button onPress={() => { riveRef.current?.fireState('MainState', 'Finish') }}>
                Finish!
            </Button>
        </View>
    )
}

export default SpeedTestButton`

### Animation files:
[start_button.zip](https://github.com/rive-app/rive-react-native/files/12481319/start_button.zip)

### Expected behavior
I just wanted to navigate between the screens

#### Screenshots
![crash](https://github.com/rive-app/rive-react-native/assets/9341070/fa574f28-4dfe-4dac-b1f2-c47646d7aea2)

### Device & Versions (please complete the following information)
- Device: [LDPlayer, last version, and Android Emulator (Android 13.0 Google APIs | x86_64 ] 
- OS: [Android SDK API Level 33]
- NPM Version: 9.6.6

#### Additional context
Its a button animation, actually, even if you stop the animation and change the screens it crashes and shows the error like in the screenshoot.

**Comment by WooMinGy** [comment]
same issue

**Comment by HayesGordon** [comment]
Hi there! I can replicate the issue and we're investigating a fix 👍

**Comment by ShivamJoker** [comment]
I am also getting:
```sh
FATAL EXCEPTION: main

java.lang.IllegalArgumentException: Failed requirement.

FATAL EXCEPTION: main
Process: com.learnaws, PID: 19530
java.lang.IllegalArgumentException: Failed requirement.
	at app.rive.runtime.kotlin.controllers.RiveFileController.release(RiveFileController.kt:697)
	at app.rive.runtime.kotlin.RiveViewLifecycleObserver.onDestroy(RiveAnimationView.kt:914)
	at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:29)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.kt:266)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:283)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
	at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:88)
	at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3196)
	at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:742)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:745)
	at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:672)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:776)
	at androidx.fragment.app.DefaultSpecialEffectsController$4$1.run(DefaultSpecialEffectsController.java:259)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8219)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by HayesGordon** [comment]
Hi all, this should be fixed in [v6.1.1](https://github.com/rive-app/rive-react-native/releases/tag/v6.1.1)

Please reopen if you run into issues or edge cases. Thanks for all the reports.
