### ISSUE TITLE
Android build crash 

### ISSUE THREAD

**Issue by hieuptit93** [rive-app/rive-react-native#199]
### Description

`java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.stepup.tofuapp.dev/app_lib/librive-android.so"...
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7828)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7577)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.stepup.tofuapp.dev/app_lib/librive-android.so"...
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2522)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2492)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8323)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7828) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7577) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) `

### Device & Versions

react-native: 0..70.13
rive-react-native: 6.0.4

### Added this section to app.gradle android section:

`packagingOptions {
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
    }
`

**Comment by MennatullahMohamed** [comment]
@hieuptit93 Did you find a solution for this issue? I'm facing it  too

react-native: 0.68.5
rive-react-native: 6.0.4

**Comment by evarouss** [comment]
Hi @MennatullahMohamed and @hieuptit93 

Did you end-up finding a solution here ?
I'm running into the same issue

**Comment by adstr123** [comment]
@hieuptit93 @MennatullahMohamed @evarouss Also facing this issue.

`"rive-react-native": "9.4.0",`

```gradle
ext {
        buildToolsVersion = "35.0.0"
        minSdkVersion = 23
        compileSdkVersion = 35
        targetSdkVersion = 35
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.25"
        agpVersion = '8.6.1'
    }
```
